backend:
  name: github
  repo: Arunphalke/ulitra-v2
  branch: main
media_folder: "images"
public_folder: "/images"
collections:
  - name: "products"
    label: "Products"
    folder: "products"
    create: true
    fields:
      - {label: "Code", name: "code", widget: "number"}
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Link", name: "link", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
